apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeapp-deployment
  labels:
    app: homeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeapp
  template:
    metadata:
      labels:
        app: homeapp
    spec:
      containers:
        - name: homeapp-container
          image: veerabhadraswami/homeapp:1.3
          ports:
            - containerPort: 80
